//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGestFacturationDeau
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture
    {
        public int IdF { get; set; }
        public int IdC { get; set; }
        public decimal Prix { get; set; }
        public System.DateTime DateFac { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public string Paye { get; set; }
    
        public virtual Compteur Compteur { get; set; }
    }
}
